"""
End-to-end tests for GoalCraft API.

These tests hit the actual running backend at http://localhost:8000.
Make sure the backend is running: docker-compose up -d
"""

import pytest
import httpx
from datetime import datetime, timedelta


BASE_URL = "http://localhost:8000"


@pytest.fixture
def client():
    """HTTP client for tests."""
    return httpx.Client(base_url=BASE_URL, timeout=60.0)


class TestHealthCheck:
    """Test health check endpoint."""

    def test_health_check(self, client):
        """Health endpoint returns healthy status."""
        response = client.get("/health")
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "healthy"
        assert data["service"] == "goalcraft-api"


class TestGoalCreation:
    """Test goal creation flow."""

    def test_create_goal_basic(self, client):
        """Create a goal with title only."""
        response = client.post(
            "/api/goals",
            json={"title": "Test Goal Basic"}
        )
        assert response.status_code == 201
        data = response.json()
        assert data["title"] == "Test Goal Basic"
        assert data["id"] is not None
        assert data["user_id"] is not None

    def test_create_goal_with_description(self, client):
        """Create a goal with title and description."""
        response = client.post(
            "/api/goals",
            json={
                "title": "Learn Python",
                "description": "Master Python programming"
            }
        )
        assert response.status_code == 201
        data = response.json()
        assert data["title"] == "Learn Python"
        assert data["description"] == "Master Python programming"

    def test_create_goal_with_target_date(self, client):
        """Create a goal with target date."""
        target = (datetime.now() + timedelta(days=90)).isoformat()
        response = client.post(
            "/api/goals",
            json={
                "title": "Run a Marathon",
                "target_date": target
            }
        )
        assert response.status_code == 201
        data = response.json()
        assert data["title"] == "Run a Marathon"
        assert data["target_date"] is not None

    def test_create_goal_generates_milestones(self, client):
        """Create a goal and verify Claude generates milestones."""
        target = (datetime.now() + timedelta(days=60)).isoformat()
        response = client.post(
            "/api/goals",
            json={
                "title": "Learn Guitar",
                "description": "Play basic songs",
                "target_date": target
            }
        )
        assert response.status_code == 201
        data = response.json()

        # Should have milestones generated by Claude
        assert "milestones" in data
        assert len(data["milestones"]) >= 3

        # Check milestone structure
        for milestone in data["milestones"]:
            assert "id" in milestone
            assert "title" in milestone
            assert "description" in milestone
            assert milestone["status"] == "pending"

    def test_create_goal_validation_empty_title(self, client):
        """Cannot create goal with empty title."""
        response = client.post(
            "/api/goals",
            json={"title": ""}
        )
        assert response.status_code == 422


class TestGoalRetrieval:
    """Test goal retrieval flow."""

    def test_list_goals(self, client):
        """List goals returns array."""
        response = client.get("/api/goals")
        assert response.status_code == 200
        assert isinstance(response.json(), list)

    def test_list_goals_after_creation(self, client):
        """List goals includes newly created goal."""
        # Create a goal
        create_resp = client.post(
            "/api/goals",
            json={"title": "Test Goal for Listing"}
        )
        goal_id = create_resp.json()["id"]

        # List goals
        response = client.get("/api/goals")
        assert response.status_code == 200
        data = response.json()
        ids = [g["id"] for g in data]
        assert goal_id in ids

    def test_get_goal_by_id(self, client):
        """Get a specific goal by ID."""
        # Create a goal
        create_response = client.post(
            "/api/goals",
            json={"title": "Goal to Retrieve"}
        )
        goal_id = create_response.json()["id"]

        # Get the goal
        response = client.get(f"/api/goals/{goal_id}")
        assert response.status_code == 200
        data = response.json()
        assert data["id"] == goal_id
        assert data["title"] == "Goal to Retrieve"
        assert "milestones" in data

    def test_get_goal_not_found(self, client):
        """Get non-existent goal returns 404."""
        response = client.get("/api/goals/99999")
        assert response.status_code == 404


class TestMilestoneManagement:
    """Test milestone management flow."""

    def test_list_milestones_for_goal(self, client):
        """List milestones for a specific goal."""
        # Create a goal with milestones
        target = (datetime.now() + timedelta(days=30)).isoformat()
        create_response = client.post(
            "/api/goals",
            json={
                "title": "Goal with Milestones",
                "target_date": target
            }
        )
        goal_id = create_response.json()["id"]

        # Get milestones
        response = client.get(f"/api/goals/{goal_id}/milestones")
        assert response.status_code == 200
        assert isinstance(response.json(), list)

    def test_update_milestone_status(self, client):
        """Update milestone status to completed."""
        # Create a goal with milestones
        target = (datetime.now() + timedelta(days=30)).isoformat()
        create_response = client.post(
            "/api/goals",
            json={
                "title": "Goal for Milestone Update",
                "target_date": target
            }
        )
        goal_data = create_response.json()

        if not goal_data.get("milestones"):
            pytest.skip("No milestones generated")

        milestone_id = goal_data["milestones"][0]["id"]

        # Update milestone status
        response = client.patch(
            f"/api/milestones/{milestone_id}",
            json={"status": "completed"}
        )
        assert response.status_code == 200
        assert response.json()["status"] == "completed"

    def test_update_milestone_status_to_in_progress(self, client):
        """Update milestone status to in_progress."""
        target = (datetime.now() + timedelta(days=30)).isoformat()
        create_response = client.post(
            "/api/goals",
            json={
                "title": "Goal for Progress Update",
                "target_date": target
            }
        )
        goal_data = create_response.json()

        if not goal_data.get("milestones"):
            pytest.skip("No milestones generated")

        milestone_id = goal_data["milestones"][0]["id"]

        response = client.patch(
            f"/api/milestones/{milestone_id}",
            json={"status": "in_progress"}
        )
        assert response.status_code == 200
        assert response.json()["status"] == "in_progress"

    def test_update_milestone_not_found(self, client):
        """Update non-existent milestone returns 404."""
        response = client.patch(
            "/api/milestones/99999",
            json={"status": "completed"}
        )
        assert response.status_code == 404


class TestGoalDeletion:
    """Test goal deletion flow."""

    def test_delete_goal(self, client):
        """Delete a goal."""
        # Create a goal
        create_response = client.post(
            "/api/goals",
            json={"title": "Goal to Delete"}
        )
        goal_id = create_response.json()["id"]

        # Delete the goal
        response = client.delete(f"/api/goals/{goal_id}")
        assert response.status_code == 204

        # Verify it's gone
        get_response = client.get(f"/api/goals/{goal_id}")
        assert get_response.status_code == 404

    def test_delete_goal_not_found(self, client):
        """Delete non-existent goal returns 404."""
        response = client.delete("/api/goals/99999")
        assert response.status_code == 404


class TestFullWorkflow:
    """Test complete user workflow."""

    def test_complete_goal_workflow(self, client):
        """Test the complete workflow: create goal -> track milestones -> complete."""
        # 1. Create a goal
        target = (datetime.now() + timedelta(days=30)).isoformat()
        create_response = client.post(
            "/api/goals",
            json={
                "title": "Complete Workflow Test",
                "description": "Test the full goal tracking workflow",
                "target_date": target
            }
        )
        assert create_response.status_code == 201
        goal_data = create_response.json()
        goal_id = goal_data["id"]

        # 2. Verify goal appears in list
        list_response = client.get("/api/goals")
        assert list_response.status_code == 200
        goals = list_response.json()
        assert any(g["id"] == goal_id for g in goals)

        # 3. Get goal details with milestones
        detail_response = client.get(f"/api/goals/{goal_id}")
        assert detail_response.status_code == 200
        goal_detail = detail_response.json()
        assert "milestones" in goal_detail

        # 4. Update first milestone to in_progress then completed
        if goal_detail["milestones"]:
            first_milestone_id = goal_detail["milestones"][0]["id"]

            progress_response = client.patch(
                f"/api/milestones/{first_milestone_id}",
                json={"status": "in_progress"}
            )
            assert progress_response.status_code == 200

            complete_response = client.patch(
                f"/api/milestones/{first_milestone_id}",
                json={"status": "completed"}
            )
            assert complete_response.status_code == 200
            assert complete_response.json()["status"] == "completed"

        # 5. Verify milestone status persisted
        final_response = client.get(f"/api/goals/{goal_id}")
        assert final_response.status_code == 200
        if final_response.json()["milestones"]:
            assert final_response.json()["milestones"][0]["status"] == "completed"

        # 6. Clean up
        client.delete(f"/api/goals/{goal_id}")
